<a href="https://colab.research.google.com/github/hirasalim/numpy-assignment/blob/main/Numpy_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dure hira
896854

task 1 create array and find


In [11]:
import numpy as np

marks=np.array([10, 20, 30, 40, 50])
print(np.sum(marks))
print(np.min(marks))
print(np.max(marks))
print(np.mean(marks))

150
10
50
30.0


task 2 Display only the values greater than or equal to 50.


In [12]:
marks=np.array([45, 80, 30, 90, 55, 20])
print(marks[marks >= 50])


[80 90 55]


task 3 create array and change into 2 rows and 3 column


In [13]:
marks=np.array([1, 2, 3, 4, 5, 6])
new_mark=marks.reshape(2,3)
print(new_mark)

[[1 2 3]
 [4 5 6]]


task 4 Generate 10 random marks between 40 and 100. and find


In [14]:
import numpy as np

marks = np.random.randint(40, 101, 10)

print(marks)

print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))



[92 52 82 90 97 93 79 84 42 50]
76.1
97
42


task 5 pssing marks are 50 find

In [15]:
import numpy as np

marks = np.array([35, 67, 89, 45, 90, 22, 70, 58])

passed = marks[marks >= 50]
failed = marks[marks < 50]

print("Passed:", passed)
print("Failed:", failed)
print("Passed students:", len(passed))
print("Failed students:", len(failed))

Passed: [67 89 90 70 58]
Failed: [35 45 22]
Passed students: 5
Failed students: 3


hands on practice

In [16]:

#IMPORT NUMPY

import numpy as np
# PYTHON list
marks = [60,20,50,90,30]
print(marks)
#NUMPY LIST
marks = np.array([70,30,40,90,80])
print(marks + 5)


[60, 20, 50, 90, 30]
[75 35 45 95 85]


In [17]:
# ONE DIMENSIONAL AARAY
numbers = np.array([10, 20, 30, 40])

print(numbers)
#two dimension aray
marks = np.array([
    [10,20,30,40,50],
    [50,60,70,80,90]
    ])
print(marks)



[10 20 30 40]
[[10 20 30 40 50]
 [50 60 70 80 90]]


In [18]:
#array properties in numpy
marks = np.array([
    [70,30,40,90,80],
    [40,50,30,70,90],
    [90,40,80,70,50]
    ])
print(marks.ndim)
print(marks.shape)
print(marks.size)
print(marks.dtype)


2
(3, 5)
15
int64


In [19]:

#indexing
marks = np.array([70,30,40,90,80])
print(marks[0])

#NEGATIVE INDEXING
print(marks[-2])


# indexing in 2d

marks = np.array([
    [20,60,50,70,80],
    [70,50,10,30,90]
    ])
print(marks[0, 2])
print(marks[1, -2])

# slicing
marks = np.array([80,30,60,90,70])
print(marks[1:4])

marks = np.array([
    [70,30,40,90,80],
    [40,50,30,70,90]
    ])
print(marks[1,1:4])

# VACTORIZED OPERATION
numbers = np.array([10, 20, 30, 40])
print(numbers + 5)
print(numbers - 5)
print(numbers * 2)
print(numbers / 2)






70
90
50
30
[30 60 90]
[50 30 70]
[15 25 35 45]
[ 5 15 25 35]
[20 40 60 80]
[ 5. 10. 15. 20.]


In [19]:
# OPERATION BETWEEN TWO ARRAY
a = np.array([10, 20, 30])

b = np.array([1, 2, 3])
print(a + b)

In [29]:
# MATHEMATICAL FUNCTION

numbers = np.array([4, 9, 16, 25])

print(np.sqrt(numbers))
print(np.power(numbers, 2))
print(np.abs(numbers))


[2. 3. 4. 5.]
[ 16  81 256 625]
[ 4  9 16 25]


In [31]:
#round number
numbers = np.array([4.2, 5.7, 8.9])

print(np.round(numbers))

[4. 6. 9.]


In [32]:
#aggergation function
marks = np.array([70, 85, 60, 95, 80])
print(np.sum(marks))
print(np.min(marks))
print(np.max(marks))
print(np.mean(marks))
print(np.median(marks))
print(np.std(marks))
print(np.var(marks))

390
60
95
78.0
80.0
12.083045973594572
146.0


In [33]:
# CONDITION in numpy
marks = np.array([30, 50, 80, 45, 90, 20])

print(marks >= 50)

print(marks >= 50)


[False  True  True False  True False]
[False  True  True False  True False]


In [34]:
# filtering data
marks = np.array([30, 50, 80, 45, 90, 20])

passed = marks[marks >= 50]

print(passed)
# failed
failed = marks[marks < 50]

print(failed)

[50 80 90]
[30 45 20]


In [35]:
# reshape
numbers = np.array([1, 2, 3, 4, 5, 6])
new_array = numbers.reshape(2, 3)

print(new_array)

[[1 2 3]
 [4 5 6]]


In [37]:
# FLATTEN DATA
## `flatten changes a multi-dimensional array into a one-dimensional array.

data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(data.flatten())

[1 2 3 4 5 6]


In [40]:
# USEFULL NUMPY OPERATION
print(np.zeros(5))
print(np.ones(5))
print(np.arange(1, 11))
marks = np.random.randint(40, 100, 10)

print(marks)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10]
[50 91 72 50 78 85 79 86 50 89]
